name: Lighthouse CI
on: deployment_status
jobs:
  generate_lighthouse_audit:
    if: github.event.deployment_status.state == 'success'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Audit preview URL with Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          budgetPath: ./perf-budget.json
          temporaryPublicStorage: temporaryPublicStorage